# Generated by Django 3.2.4 on 2021-09-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('summary', models.TextField()),
                ('time_taken', models.FloatField(default=0.0)),
            ],
        ),
    ]
